apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.container.Port }}
    targetPort: {{ .Values.container.Port }}
  type: ClusterIP

